# Generated by Django 4.1.5 on 2023-01-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='des',
            field=models.TextField(),
        ),
    ]
